### PR TITLE
Added windowtitle to contextmenu + bumped version

### PR DESCRIPTION
**Pull request by sproclavism**
Hi,

I've added the title of the window for personal use.
This pull request is to notify you of that, in case you would be interested to use it.

Cheers

### CODE REVIEW

**Comment by palmerj** [comment]
Could this please be published as an update on the webstore? If not how do I install this for personal use?

**Comment by sproclavism** [comment]
@palmerj I'm not the publisher of that extension so I can't do that. I wish I could.

Simply download my version and place the files in a folder. Then you will load that folder as an unpacked extension. If you're not sure how to do that, [this](https://www.thesslstore.com/blog/install-a-chrome-extension/) or [this](https://stackoverflow.com/a/24577660) may be of help. If neither of those helps you out just google something along the lines of "chrome load unpacked extension".

**Comment by jfsl** [comment]
This is now merged and published to the webstore. It should become available within 60 minutes.

@Zarnaik I am terribly sorry for missing this! Thank you very much for making this extension better.

**Comment by sproclavism** [comment]
Cheers.

**Comment by palmerj** [comment]
Thank you both!

**Pull request merged**
